project_id = "bbgfenuwyaytocvjjpcs"

[functions.process-session]
verify_jwt = false

[functions.generate-parent-message]
verify_jwt = false

[functions.generate-quick-notes-summary]
verify_jwt = false

[functions.generate-parent-messages]
verify_jwt = false

[functions.extract-text]
verify_jwt = false

[functions.grade-paper]
verify_jwt = false

[functions.grade-organizer]
verify_jwt = false

[functions.generate-pdf-report]
verify_jwt = false

[functions.format-teacher-note]
verify_jwt = false

[functions.grade-ela]
verify_jwt = false
